// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"database/sql"
	"time"
)

type AuthorizationHistory struct {
	UserID       int64
	ClientID     string
	AuthorizedAt time.Time
}

type Client struct {
	ID              string
	SecretHash      string
	Name            string
	PictureUrl      sql.NullString
	CallbackUrls    string
	TokenExpiration int64
}

type User struct {
	ID             int64
	Email          string
	AvatarUrl      sql.NullString
	HashedPassword sql.NullString
	IsAdmin        bool
}
