// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"database/sql"
	"time"
)

type AuthorizationHistory struct {
	UserID       int64
	ClientID     string
	AuthorizedAt time.Time
}

type Client struct {
	ID                 string
	SecretHash         string
	Name               string
	PictureUrl         sql.NullString
	AuthCallbackUrls   string
	LogoutCallbackUrls string
	TokenExpiration    int64
	CreatedAt          time.Time
}

type Session struct {
	ID        string
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
	ClientID  sql.NullString
	Os        sql.NullString
	Browser   sql.NullString
}

type User struct {
	ID             int64
	Email          string
	AvatarUrl      sql.NullString
	HashedPassword sql.NullString
	IsAdmin        bool
	CreatedAt      time.Time
}
